export const GAME_GET_REQUEST = "GAME_GET_REQUEST";
export const GAME_GET_SUCCESS = "GAME_GET_SUCCESS";
export const GAME_GET_FAIL = "GAME_GET_FAIL";
export const GAME_GET_RESET = "GAME_GET_RESET";

export const GAME_GET_TURN_REQUEST = "GAME_GET_TURN_REQUEST";
export const GAME_GET_TURN_SUCCESS = "GAME_GET_TURN_SUCCESS";
export const GAME_GET_TURN_FAIL = "GAME_GET_TURN_FAIL";

export const GAME_UPDATE_TURN_REQUEST = "GAME_UPDATE_TURN_REQUEST";
export const GAME_UPDATE_TURN_SUCCESS = "GAME_UPDATE_TURN_SUCCESS";
export const GAME_UPDATE_TURN_FAIL = "GAME_UPDATE_TURN_FAIL";
