export const MODAL_SET_REQUEST = "MODAL_SET_REQUEST";
export const MODAL_SET_SUCCESS = "MODAL_SET_SUCCESS";
export const MODAL_SET_FAIL = "MODAL_SET_FAIL";
export const MODAL_SET_RESET = "MODAL_SET_RESET";
